sudo: required
services:
  - docker

before_install:
  - docker build -t takaishotaro/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true takaishotaro/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-761917515195"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
